version: '3.8'
name: firecrawl

services:
  playwright-service:
    image: ghcr.io/mendableai/playwright-service:latest
    environment:
      PORT: 3000
    networks:
      - firecrawl-net

  api:
    image: ghcr.io/mendableai/firecrawl:latest
    environment:
      REDIS_URL: redis://redis:6379
      PLAYWRIGHT_MICROSERVICE_URL: http://playwright-service:3000/scrape
      HOST: 0.0.0.0
      PORT: 3002
      OLLAMA_BASE_URL: http://127.0.0.1:11434
      MODEL_NAME: llama3.1
    ports:
      - "3002:3002"
    depends_on:
      - redis
      - playwright-service
    networks:
      - firecrawl-net

  redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0
    networks:
      - firecrawl-net

networks:
  firecrawl-net:
    driver: bridge
